/**
 * IATA Airport Code Directory — 200+ airports
 * Maintained separately for easy updates.
 * Last updated: 2026-07
 * To add a new airport: { IATA: { city, country, name } }
 */

const IATA_MAP = {
  // ── SOUTHEAST ASIA ──────────────────────────────────────────
  SIN: { city: 'Singapore', country: 'Singapore', name: 'Changi Airport' },
  BKK: { city: 'Bangkok', country: 'Thailand', name: 'Suvarnabhumi Airport' },
  DMK: { city: 'Bangkok', country: 'Thailand', name: 'Don Mueang Airport' },
  HKT: { city: 'Phuket', country: 'Thailand', name: 'Phuket International Airport' },
  CNX: { city: 'Chiang Mai', country: 'Thailand', name: 'Chiang Mai International Airport' },
  KBV: { city: 'Krabi', country: 'Thailand', name: 'Krabi Airport' },
  USM: { city: 'Koh Samui', country: 'Thailand', name: 'Samui Airport' },
  SGN: { city: 'Ho Chi Minh City', country: 'Vietnam', name: 'Tan Son Nhat Airport' },
  HAN: { city: 'Hanoi', country: 'Vietnam', name: 'Noi Bai International Airport' },
  DAD: { city: 'Da Nang', country: 'Vietnam', name: 'Da Nang International Airport' },
  PQC: { city: 'Phu Quoc', country: 'Vietnam', name: 'Phu Quoc International Airport' },
  HUI: { city: 'Hue', country: 'Vietnam', name: 'Phu Bai International Airport' },
  // KTI = Techo Pochentong International Airport, Phnom Penh (new airport, opened 2026)
  KTI: { city: 'Phnom Penh', country: 'Cambodia', name: 'Techo Pochentong International Airport' },
  PNH: { city: 'Phnom Penh', country: 'Cambodia', name: 'Phnom Penh International Airport (legacy)' },
  REP: { city: 'Siem Reap', country: 'Cambodia', name: 'Siem Reap–Angkor International Airport' },
  RGN: { city: 'Yangon', country: 'Myanmar', name: 'Yangon International Airport' },
  MDL: { city: 'Mandalay', country: 'Myanmar', name: 'Mandalay International Airport' },
  VTE: { city: 'Vientiane', country: 'Laos', name: 'Wattay International Airport' },
  MNL: { city: 'Manila', country: 'Philippines', name: 'Ninoy Aquino International Airport' },
  CEB: { city: 'Cebu', country: 'Philippines', name: 'Mactan-Cebu International Airport' },
  DVO: { city: 'Davao', country: 'Philippines', name: 'Francisco Bangoy International Airport' },
  KUL: { city: 'Kuala Lumpur', country: 'Malaysia', name: 'Kuala Lumpur International Airport' },
  BKI: { city: 'Kota Kinabalu', country: 'Malaysia', name: 'Kota Kinabalu International Airport' },
  PEN: { city: 'Penang', country: 'Malaysia', name: 'Penang International Airport' },
  CGK: { city: 'Jakarta', country: 'Indonesia', name: 'Soekarno-Hatta International Airport' },
  DPS: { city: 'Bali', country: 'Indonesia', name: 'Ngurah Rai International Airport' },
  SUB: { city: 'Surabaya', country: 'Indonesia', name: 'Juanda International Airport' },
  UPG: { city: 'Makassar', country: 'Indonesia', name: 'Sultan Hasanuddin Airport' },
  LOP: { city: 'Lombok', country: 'Indonesia', name: 'Lombok International Airport' },
  BWN: { city: 'Bandar Seri Begawan', country: 'Brunei', name: 'Brunei International Airport' },
  // ── EAST ASIA ───────────────────────────────────────────────
  HND: { city: 'Tokyo', country: 'Japan', name: 'Haneda Airport' },
  NRT: { city: 'Tokyo', country: 'Japan', name: 'Narita International Airport' },
  KIX: { city: 'Osaka', country: 'Japan', name: 'Kansai International Airport' },
  ITM: { city: 'Osaka', country: 'Japan', name: 'Itami Airport' },
  CTS: { city: 'Sapporo', country: 'Japan', name: 'New Chitose Airport' },
  FUK: { city: 'Fukuoka', country: 'Japan', name: 'Fukuoka Airport' },
  OKA: { city: 'Okinawa', country: 'Japan', name: 'Naha Airport' },
  NGO: { city: 'Nagoya', country: 'Japan', name: 'Chubu Centrair International Airport' },
  ICN: { city: 'Seoul', country: 'South Korea', name: 'Incheon International Airport' },
  GMP: { city: 'Seoul', country: 'South Korea', name: 'Gimpo International Airport' },
  PUS: { city: 'Busan', country: 'South Korea', name: 'Gimhae International Airport' },
  CJU: { city: 'Jeju', country: 'South Korea', name: 'Jeju International Airport' },
  HKG: { city: 'Hong Kong', country: 'Hong Kong', name: 'Hong Kong International Airport' },
  MFM: { city: 'Macau', country: 'Macau', name: 'Macau International Airport' },
  TPE: { city: 'Taipei', country: 'Taiwan', name: 'Taoyuan International Airport' },
  TSA: { city: 'Taipei', country: 'Taiwan', name: 'Taipei Songshan Airport' },
  KHH: { city: 'Kaohsiung', country: 'Taiwan', name: 'Kaohsiung International Airport' },
  PEK: { city: 'Beijing', country: 'China', name: 'Beijing Capital International Airport' },
  PKX: { city: 'Beijing', country: 'China', name: 'Beijing Daxing International Airport' },
  PVG: { city: 'Shanghai', country: 'China', name: 'Shanghai Pudong International Airport' },
  SHA: { city: 'Shanghai', country: 'China', name: 'Shanghai Hongqiao Airport' },
  CAN: { city: 'Guangzhou', country: 'China', name: 'Guangzhou Baiyun International Airport' },
  SZX: { city: 'Shenzhen', country: 'China', name: "Shenzhen Bao'an International Airport" },
  CTU: { city: 'Chengdu', country: 'China', name: 'Chengdu Tianfu International Airport' },
  XIY: { city: "Xi'an", country: 'China', name: "Xi'an Xianyang International Airport" },
  HGH: { city: 'Hangzhou', country: 'China', name: 'Hangzhou Xiaoshan International Airport' },
  CKG: { city: 'Chongqing', country: 'China', name: 'Chongqing Jiangbei International Airport' },
  WUH: { city: 'Wuhan', country: 'China', name: 'Wuhan Tianhe International Airport' },
  // ── SOUTH ASIA ──────────────────────────────────────────────
  DEL: { city: 'New Delhi', country: 'India', name: 'Indira Gandhi International Airport' },
  BOM: { city: 'Mumbai', country: 'India', name: 'Chhatrapati Shivaji Maharaj International Airport' },
  BLR: { city: 'Bengaluru', country: 'India', name: 'Kempegowda International Airport' },
  MAA: { city: 'Chennai', country: 'India', name: 'Chennai International Airport' },
  HYD: { city: 'Hyderabad', country: 'India', name: 'Rajiv Gandhi International Airport' },
  CCU: { city: 'Kolkata', country: 'India', name: 'Netaji Subhas Chandra Bose Airport' },
  AMD: { city: 'Ahmedabad', country: 'India', name: 'Sardar Vallabhbhai Patel Airport' },
  COK: { city: 'Kochi', country: 'India', name: 'Cochin International Airport' },
  CMB: { city: 'Colombo', country: 'Sri Lanka', name: 'Bandaranaike International Airport' },
  DAC: { city: 'Dhaka', country: 'Bangladesh', name: 'Hazrat Shahjalal International Airport' },
  KTM: { city: 'Kathmandu', country: 'Nepal', name: 'Tribhuvan International Airport' },
  KHI: { city: 'Karachi', country: 'Pakistan', name: 'Jinnah International Airport' },
  LHE: { city: 'Lahore', country: 'Pakistan', name: 'Allama Iqbal International Airport' },
  ISB: { city: 'Islamabad', country: 'Pakistan', name: 'Islamabad International Airport' },
  // ── MIDDLE EAST ─────────────────────────────────────────────
  DXB: { city: 'Dubai', country: 'UAE', name: 'Dubai International Airport' },
  DWC: { city: 'Dubai', country: 'UAE', name: 'Al Maktoum International Airport' },
  AUH: { city: 'Abu Dhabi', country: 'UAE', name: 'Zayed International Airport' },
  SHJ: { city: 'Sharjah', country: 'UAE', name: 'Sharjah International Airport' },
  DOH: { city: 'Doha', country: 'Qatar', name: 'Hamad International Airport' },
  BAH: { city: 'Manama', country: 'Bahrain', name: 'Bahrain International Airport' },
  KWI: { city: 'Kuwait City', country: 'Kuwait', name: 'Kuwait International Airport' },
  MCT: { city: 'Muscat', country: 'Oman', name: 'Muscat International Airport' },
  AMM: { city: 'Amman', country: 'Jordan', name: 'Queen Alia International Airport' },
  BEY: { city: 'Beirut', country: 'Lebanon', name: 'Rafic Hariri International Airport' },
  TLV: { city: 'Tel Aviv', country: 'Israel', name: 'Ben Gurion International Airport' },
  RUH: { city: 'Riyadh', country: 'Saudi Arabia', name: 'King Khalid International Airport' },
  JED: { city: 'Jeddah', country: 'Saudi Arabia', name: 'King Abdulaziz International Airport' },
  DMM: { city: 'Dammam', country: 'Saudi Arabia', name: 'King Fahd International Airport' },
  // ── EUROPE – WESTERN ────────────────────────────────────────
  LHR: { city: 'London', country: 'United Kingdom', name: 'Heathrow Airport' },
  LGW: { city: 'London', country: 'United Kingdom', name: 'Gatwick Airport' },
  STN: { city: 'London', country: 'United Kingdom', name: 'Stansted Airport' },
  LTN: { city: 'London', country: 'United Kingdom', name: 'Luton Airport' },
  MAN: { city: 'Manchester', country: 'United Kingdom', name: 'Manchester Airport' },
  EDI: { city: 'Edinburgh', country: 'United Kingdom', name: 'Edinburgh Airport' },
  GLA: { city: 'Glasgow', country: 'United Kingdom', name: 'Glasgow Airport' },
  CDG: { city: 'Paris', country: 'France', name: 'Charles de Gaulle Airport' },
  ORY: { city: 'Paris', country: 'France', name: 'Orly Airport' },
  LYS: { city: 'Lyon', country: 'France', name: 'Lyon-Saint Exupery Airport' },
  NCE: { city: 'Nice', country: 'France', name: "Nice Cote d'Azur Airport" },
  MRS: { city: 'Marseille', country: 'France', name: 'Marseille Provence Airport' },
  FRA: { city: 'Frankfurt', country: 'Germany', name: 'Frankfurt Airport' },
  MUC: { city: 'Munich', country: 'Germany', name: 'Munich Airport' },
  BER: { city: 'Berlin', country: 'Germany', name: 'Berlin Brandenburg Airport' },
  DUS: { city: 'Dusseldorf', country: 'Germany', name: 'Dusseldorf Airport' },
  HAM: { city: 'Hamburg', country: 'Germany', name: 'Hamburg Airport' },
  CGN: { city: 'Cologne', country: 'Germany', name: 'Cologne Bonn Airport' },
  STR: { city: 'Stuttgart', country: 'Germany', name: 'Stuttgart Airport' },
  AMS: { city: 'Amsterdam', country: 'Netherlands', name: 'Schiphol Airport' },
  EIN: { city: 'Eindhoven', country: 'Netherlands', name: 'Eindhoven Airport' },
  BRU: { city: 'Brussels', country: 'Belgium', name: 'Brussels Airport' },
  CRL: { city: 'Brussels', country: 'Belgium', name: 'Brussels South Charleroi Airport' },
  ZRH: { city: 'Zurich', country: 'Switzerland', name: 'Zurich Airport' },
  GVA: { city: 'Geneva', country: 'Switzerland', name: 'Geneva Airport' },
  VIE: { city: 'Vienna', country: 'Austria', name: 'Vienna International Airport' },
  FCO: { city: 'Rome', country: 'Italy', name: 'Leonardo da Vinci–Fiumicino Airport' },
  CIA: { city: 'Rome', country: 'Italy', name: 'Ciampino Airport' },
  MXP: { city: 'Milan', country: 'Italy', name: 'Malpensa Airport' },
  LIN: { city: 'Milan', country: 'Italy', name: 'Linate Airport' },
  BGY: { city: 'Milan', country: 'Italy', name: 'Bergamo Orio al Serio Airport' },
  VCE: { city: 'Venice', country: 'Italy', name: 'Venice Marco Polo Airport' },
  MAD: { city: 'Madrid', country: 'Spain', name: 'Adolfo Suarez Madrid-Barajas Airport' },
  BCN: { city: 'Barcelona', country: 'Spain', name: 'Barcelona-El Prat Airport' },
  AGP: { city: 'Malaga', country: 'Spain', name: 'Malaga-Costa del Sol Airport' },
  PMI: { city: 'Palma de Mallorca', country: 'Spain', name: 'Palma de Mallorca Airport' },
  LIS: { city: 'Lisbon', country: 'Portugal', name: 'Humberto Delgado Airport' },
  OPO: { city: 'Porto', country: 'Portugal', name: 'Francisco Sa Carneiro Airport' },
  CPH: { city: 'Copenhagen', country: 'Denmark', name: 'Copenhagen Airport' },
  ARN: { city: 'Stockholm', country: 'Sweden', name: 'Stockholm Arlanda Airport' },
  GOT: { city: 'Gothenburg', country: 'Sweden', name: 'Gothenburg Landvetter Airport' },
  OSL: { city: 'Oslo', country: 'Norway', name: 'Oslo Gardermoen Airport' },
  HEL: { city: 'Helsinki', country: 'Finland', name: 'Helsinki-Vantaa Airport' },
  RIX: { city: 'Riga', country: 'Latvia', name: 'Riga International Airport' },
  TLL: { city: 'Tallinn', country: 'Estonia', name: 'Tallinn Airport' },
  VNO: { city: 'Vilnius', country: 'Lithuania', name: 'Vilnius Airport' },
  WAW: { city: 'Warsaw', country: 'Poland', name: 'Warsaw Chopin Airport' },
  KRK: { city: 'Krakow', country: 'Poland', name: 'John Paul II International Airport Krakow' },
  PRG: { city: 'Prague', country: 'Czech Republic', name: 'Vaclav Havel Airport Prague' },
  BUD: { city: 'Budapest', country: 'Hungary', name: 'Budapest Ferenc Liszt Airport' },
  OTP: { city: 'Bucharest', country: 'Romania', name: 'Henri Coanda International Airport' },
  SOF: { city: 'Sofia', country: 'Bulgaria', name: 'Sofia Airport' },
  ATH: { city: 'Athens', country: 'Greece', name: 'Athens International Airport' },
  HER: { city: 'Heraklion', country: 'Greece', name: 'Heraklion International Airport' },
  SKG: { city: 'Thessaloniki', country: 'Greece', name: 'Thessaloniki Airport' },
  IST: { city: 'Istanbul', country: 'Turkey', name: 'Istanbul Airport' },
  SAW: { city: 'Istanbul', country: 'Turkey', name: 'Sabiha Gokcen Airport' },
  AYT: { city: 'Antalya', country: 'Turkey', name: 'Antalya Airport' },
  DUB: { city: 'Dublin', country: 'Ireland', name: 'Dublin Airport' },
  // ── EUROPE – EASTERN ────────────────────────────────────────
  KBP: { city: 'Kyiv', country: 'Ukraine', name: 'Boryspil International Airport' },
  SVO: { city: 'Moscow', country: 'Russia', name: 'Sheremetyevo International Airport' },
  LED: { city: 'Saint Petersburg', country: 'Russia', name: 'Pulkovo Airport' },
  // ── NORTH AMERICA ───────────────────────────────────────────
  JFK: { city: 'New York', country: 'United States', name: 'John F. Kennedy International Airport' },
  EWR: { city: 'New York', country: 'United States', name: 'Newark Liberty International Airport' },
  LGA: { city: 'New York', country: 'United States', name: 'LaGuardia Airport' },
  LAX: { city: 'Los Angeles', country: 'United States', name: 'Los Angeles International Airport' },
  BUR: { city: 'Los Angeles', country: 'United States', name: 'Hollywood Burbank Airport' },
  SNA: { city: 'Orange County', country: 'United States', name: 'John Wayne Airport' },
  SFO: { city: 'San Francisco', country: 'United States', name: 'San Francisco International Airport' },
  SJC: { city: 'San Jose', country: 'United States', name: 'Norman Y. Mineta San Jose Airport' },
  OAK: { city: 'Oakland', country: 'United States', name: 'Metropolitan Oakland International Airport' },
  ORD: { city: 'Chicago', country: 'United States', name: "O'Hare International Airport" },
  MDW: { city: 'Chicago', country: 'United States', name: 'Midway International Airport' },
  MIA: { city: 'Miami', country: 'United States', name: 'Miami International Airport' },
  FLL: { city: 'Fort Lauderdale', country: 'United States', name: 'Fort Lauderdale-Hollywood Airport' },
  SEA: { city: 'Seattle', country: 'United States', name: 'Seattle-Tacoma International Airport' },
  BOS: { city: 'Boston', country: 'United States', name: 'Logan International Airport' },
  DEN: { city: 'Denver', country: 'United States', name: 'Denver International Airport' },
  DFW: { city: 'Dallas', country: 'United States', name: 'Dallas/Fort Worth International Airport' },
  DAL: { city: 'Dallas', country: 'United States', name: 'Dallas Love Field Airport' },
  ATL: { city: 'Atlanta', country: 'United States', name: 'Hartsfield-Jackson Atlanta Airport' },
  IAH: { city: 'Houston', country: 'United States', name: 'George Bush Intercontinental Airport' },
  HOU: { city: 'Houston', country: 'United States', name: 'William P. Hobby Airport' },
  PHX: { city: 'Phoenix', country: 'United States', name: 'Phoenix Sky Harbor Airport' },
  LAS: { city: 'Las Vegas', country: 'United States', name: 'Harry Reid International Airport' },
  MCO: { city: 'Orlando', country: 'United States', name: 'Orlando International Airport' },
  TPA: { city: 'Tampa', country: 'United States', name: 'Tampa International Airport' },
  CLT: { city: 'Charlotte', country: 'United States', name: 'Charlotte Douglas International Airport' },
  PHL: { city: 'Philadelphia', country: 'United States', name: 'Philadelphia International Airport' },
  DCA: { city: 'Washington DC', country: 'United States', name: 'Ronald Reagan Washington National Airport' },
  IAD: { city: 'Washington DC', country: 'United States', name: 'Washington Dulles International Airport' },
  MSP: { city: 'Minneapolis', country: 'United States', name: 'Minneapolis-Saint Paul Airport' },
  DTW: { city: 'Detroit', country: 'United States', name: 'Detroit Metropolitan Wayne County Airport' },
  PDX: { city: 'Portland', country: 'United States', name: 'Portland International Airport' },
  AUS: { city: 'Austin', country: 'United States', name: 'Austin-Bergstrom International Airport' },
  YVR: { city: 'Vancouver', country: 'Canada', name: 'Vancouver International Airport' },
  YYZ: { city: 'Toronto', country: 'Canada', name: 'Toronto Pearson International Airport' },
  YUL: { city: 'Montreal', country: 'Canada', name: 'Montreal-Trudeau International Airport' },
  YYC: { city: 'Calgary', country: 'Canada', name: 'Calgary International Airport' },
  YEG: { city: 'Edmonton', country: 'Canada', name: 'Edmonton International Airport' },
  YOW: { city: 'Ottawa', country: 'Canada', name: 'Ottawa Macdonald-Cartier Airport' },
  MEX: { city: 'Mexico City', country: 'Mexico', name: 'Benito Juarez International Airport' },
  CUN: { city: 'Cancun', country: 'Mexico', name: 'Cancun International Airport' },
  GDL: { city: 'Guadalajara', country: 'Mexico', name: 'Don Miguel Hidalgo International Airport' },
  // ── LATIN AMERICA ───────────────────────────────────────────
  GRU: { city: 'Sao Paulo', country: 'Brazil', name: 'Guarulhos International Airport' },
  CGH: { city: 'Sao Paulo', country: 'Brazil', name: 'Congonhas Airport' },
  GIG: { city: 'Rio de Janeiro', country: 'Brazil', name: 'Galeao International Airport' },
  BSB: { city: 'Brasilia', country: 'Brazil', name: 'Presidente Juscelino Kubitschek Airport' },
  EZE: { city: 'Buenos Aires', country: 'Argentina', name: 'Ezeiza Ministro Pistarini Airport' },
  AEP: { city: 'Buenos Aires', country: 'Argentina', name: 'Jorge Newbery Airfield' },
  SCL: { city: 'Santiago', country: 'Chile', name: 'Arturo Merino Benitez Airport' },
  BOG: { city: 'Bogota', country: 'Colombia', name: 'El Dorado International Airport' },
  LIM: { city: 'Lima', country: 'Peru', name: 'Jorge Chavez International Airport' },
  UIO: { city: 'Quito', country: 'Ecuador', name: 'Mariscal Sucre International Airport' },
  // ── AFRICA ──────────────────────────────────────────────────
  CAI: { city: 'Cairo', country: 'Egypt', name: 'Cairo International Airport' },
  JNB: { city: 'Johannesburg', country: 'South Africa', name: 'O. R. Tambo International Airport' },
  CPT: { city: 'Cape Town', country: 'South Africa', name: 'Cape Town International Airport' },
  DUR: { city: 'Durban', country: 'South Africa', name: 'King Shaka International Airport' },
  NBO: { city: 'Nairobi', country: 'Kenya', name: 'Jomo Kenyatta International Airport' },
  ADD: { city: 'Addis Ababa', country: 'Ethiopia', name: 'Addis Ababa Bole International Airport' },
  LOS: { city: 'Lagos', country: 'Nigeria', name: 'Murtala Muhammed International Airport' },
  ABV: { city: 'Abuja', country: 'Nigeria', name: 'Nnamdi Azikiwe International Airport' },
  ACC: { city: 'Accra', country: 'Ghana', name: 'Kotoka International Airport' },
  CMN: { city: 'Casablanca', country: 'Morocco', name: 'Mohammed V International Airport' },
  TUN: { city: 'Tunis', country: 'Tunisia', name: 'Tunis-Carthage International Airport' },
  ALG: { city: 'Algiers', country: 'Algeria', name: 'Houari Boumediene Airport' },
  DAR: { city: 'Dar es Salaam', country: 'Tanzania', name: 'Julius Nyerere International Airport' },
  // ── OCEANIA ─────────────────────────────────────────────────
  SYD: { city: 'Sydney', country: 'Australia', name: 'Sydney Kingsford Smith Airport' },
  MEL: { city: 'Melbourne', country: 'Australia', name: 'Melbourne Airport' },
  BNE: { city: 'Brisbane', country: 'Australia', name: 'Brisbane Airport' },
  PER: { city: 'Perth', country: 'Australia', name: 'Perth Airport' },
  ADL: { city: 'Adelaide', country: 'Australia', name: 'Adelaide Airport' },
  OOL: { city: 'Gold Coast', country: 'Australia', name: 'Gold Coast Airport' },
  CBR: { city: 'Canberra', country: 'Australia', name: 'Canberra Airport' },
  AKL: { city: 'Auckland', country: 'New Zealand', name: 'Auckland Airport' },
  CHC: { city: 'Christchurch', country: 'New Zealand', name: 'Christchurch Airport' },
  WLG: { city: 'Wellington', country: 'New Zealand', name: 'Wellington Airport' },
  NAN: { city: 'Nadi', country: 'Fiji', name: 'Nadi International Airport' },
  PPT: { city: 'Papeete', country: 'French Polynesia', name: "Faa'a International Airport" },
};

module.exports = IATA_MAP;
